spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    url: jdbc:h2:mem:testdb;MODE=mysql;


  #datasource:
    #url: jdbc:h2:mem:testdb;MODE=mysql;
    #platform: h2
    #username: sa
    #password: 
    #driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

handlebars:
  prefix: file:src/main/resources/templates/
  cache: false

server:
  servlet:
    context-path: /dev
  port: 9980
